import './global.css';
import { ReactQueryProvider } from '@common/providers/react-query-provider';
import { ThemeProvider } from '@common/providers/theme-provider';
import { AuthProvider } from '@common/providers/auth-provider';
import { Toaster } from '@common/ui/components/sonner';

export const metadata = {
  title: 'Welcome to ',
  description: 'Generated by create-nx-workspace',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body>
        <ThemeProvider>
          <ReactQueryProvider>
            <AuthProvider>{children}</AuthProvider>
          </ReactQueryProvider>
          <Toaster richColors position="top-right" />
        </ThemeProvider>
      </body>
    </html>
  );
}
